stages:
  - deploy

deploy-image:
  stage: deploy
  script:
    - '[[ -z "${HUB_REGISTRY_IMAGE}" ]] && false'
    - docker login -u "${HUB_REGISTRY_USERNAME}" -p "${HUB_REGISTRY_PASSWORD}"
    - docker build --force-rm=true --pull=true --no-cache --file Dockerfile --tag "${HUB_REGISTRY_IMAGE}:latest" .
    - docker push "${HUB_REGISTRY_IMAGE}:latest"
    - docker images "${HUB_REGISTRY_IMAGE}:latest"
    - docker history "${HUB_REGISTRY_IMAGE}:latest"
  after_script:
    - docker rmi "${HUB_REGISTRY_IMAGE}:latest"
  only:
    - master
    - tags
    - branches
  tags:
    - docker-deploy
